.gitignore
PopulateDatabase/gen_comments.py
PopulateDatabase/gen_posts.py
PopulateDatabase/gen_users.py
PopulateDatabase/populate_db.py
PopulateDatabase/requirements.txt

- Added script to generate comments in database.
- Takes number of new comments to generate as a command line argument.
- Comments are created with a random paragraph generator from the faker package.
- Selects random existing user and post for comment.
- Added script to generate posts in database.
- Takes the number of new posts to generate as a command line argument.
- Posts are created with a random paragraph generator from the faker package.
- Each post uses random existing users for the author.
- Added a script to generate users in database.
- Takes the number of new users to generate as a command line argument.
- User names are generated using the faker library.
- The default password is 'password' (sinze these users are for testing purposes).
- Text file that holds the python …

Populate db

---

.gitignore
package-lock.json
package.json
server.js

- Added .http files to the gitignore.
- Added mysql2 package.
- Used to connect with our DB. 
- Added dotenv package.
- Used to get sensitive information from a local .env file.
- Added mysql pool connection.
- Added example query route to show how to query DB and use the query results.

Db connection

---

server.js

Added system that prevents users from navigating past the login page without being logged in

Added auth middleware

---

server.js

- Added ```POST /login``` route to authenticate user credentials on login.
- If authentication is successful, responds with status code ```200``` with the user id sent in the response JSON.
- JSON format is: ```{ "user_id": id }```
- If authentication fails, responds with status code ```401``` and the following text: ```Invalid credentials```

Implemented login endpoint.

---

database_scripts/gen_comments.py
database_scripts/gen_posts.py
database_scripts/gen_users.py
database_scripts/requirements.txt

- Renamed PopulateDatabase folder to database_scripts.
- Imported and used dotenv package to load environment variables.
- Fixed error with Faker seeding value (will use system time by default).
- Fixed error on line 45 where the post_id query was using the user_id query.
- This would occasionally cause an error: ```_mysql_connector.MySQLInterfaceError: Cannot add or update a child row: a foreign key constraint fails```
-  Import and use dotenv to load the environment variables.
- Fixed the aforementioned error with the Faker seed.
- Imported and used dotenv to load the environment variables.
- Fixed that pesky Faker seeding error.
- Added python-dotenv package dependency.

Update scripts to use dotenv. Fix seed error. Fix comment bug.

---

.gitignore
server.js

Added the endpoint which allows the user to view posts on the main/home page. The parameters for the query are as follows
{
"lastID": 4,    <- the ID of the last queried post, used to avoid duplicate data
"limit": 5       <- the maximum number of posts to send in the response
}

Browse posts endpoint

---

server.js

Fixed and done from main this time

Added User signup Post request

---

Dockerfile

- Added dockerfile to build image from project.
- Image has been built and pushed to [docker hub](https://hub.docker.com/r/elmatero/proj_6_web)
🐳 That is all 🐳

Add dockerfile.

---

server.js

SQL query tested, post_id gets returned in JSON format

Post creation endpoint from main

---

server.js

Revert "Post creation endpoint from main"

---

server.js

Fixed SQL query and added missing "post" word

fixed post sql query

---

server.js

Comment endpoint done and tested with SQL query

Comment route endpoint

---

Public/Browse.html
server.js

Added infinite scrolling functionality to the browse page. It will allow you to scroll through every post in the database if you really want to.

Browse scrolling

---

server.js

- Added middleware to handle OPTIONS requests globally.
That is all

Add middleware to handle OPTIONS requests.

---

Public/Article.html
server.js

A single article can be viewed with the route /article and a query parameter of the id of the post (Ex. /article?id=3). Loads data from the GET /post endpoint into the page using some black magic I copied for Alistair.

View single article page

---

server.js

Hopefully done, check with SQL Query and it should be good
Asks for Body of comment, Comment ID and the Post it is Associated with

Finished Patch Comment

---

Public/Browse.html

The browse page now calls the /article route with the post id and the html page reads the data from the /post route. Everything seems to be working as intended.

Browse is working with the single article page!

---

Public/Browse.html
Public/Login.html
package-lock.json
package.json
server.js

- Changed getArticles to use localhost instead of 127.0.0.1.
- Added path to setCookie.
- Changed window.location.href to window.location.replace.
- Added cookie parser.
- Added cookie-parser.
- Added authChecker middleware.

Add authChecker middleware. Add cookie-parser.

---

Public/Article.html
server.js

- Changed IP address to localhost.
- Set cookies after making login/signup queries.

Fix article IP. Set server side cookies.

---

Public/Article.html
server.js

Creating a comment is now possible from a single article. Currently it only is created from the user_id of 1, but that will be changed right after this is merged and I will use the cookie to set the user_id and get the username.

Integrate create comment

---

server.js

Fix authCHecker.

---

Public/Article.html
Public/Browse.html
Public/NewPost.html
Public/Profile.html
Public/headerFuncs.js
Public/headerStyles.css

Rebuilt the header, separated functionality and styles into external files for consistency and maintainability

Header fixes not rushed

---

Public/Profile.html
server.js

Fixed an issue that causes the profile page to infinitely repeat the same posts

Profile page repeated articles fix

---

Public/Profile.html
Routes/post.js

A new endpoint for deleting posts has been added, and a button was added to your profile page which allows you to delete your own posts while browsing them. It may be too easy right now to delete a post and might be accidentally hit. Could be worth to add some sort of confirmation in the future.

Delete post functionality added

---

Public/NewPost.html

This PR solves issue #69.
- Added prompt div.
- Added promptMessage element.
- Added closePromptButton button.
- Added CSS styles for these HTML elements.
- Added showNewPostPrompt function to show the prompt, set the border color, and set the message.
- Added the hideNewPostPrompt function to hide the prompt.
- Made a call to showNewPostPrompt based on the response in the sendPost() function.

Add status prompt when creating new post.

---

Routes/comment.js
Routes/login.js
Routes/post.js
Routes/posts.js
Routes/profile.js
Routes/signup.js
server.js

This PR provides a major overhaul of the server's logging. The server will now log the request path, method, query data, and response code. This PR also includes the changes I made in PR #78, so I could get the server to start on Linux.
- Every file in the Routes folder now has logging for each route's:
- Request Method
- JSON Query Data
-  Response Code
- The server file has been updated so that each route now logs the:
- Request method
- File that was served (if applicable)
- Response Code
- Updated the "listening on" message so the link will bring us to the home page.

Logging update

---

Public/Profile.html

Added the edit post on the profile page. Closes #85.

85 edit post button

---

Public/Profile.html

This PR fixes issue #91.
The fix was just to change the link to the edit page from `./editPost.html` to `./EditPost.html`.

Fix button link to EditPost.html from Profile.html.

---

Routes/comment.js

This PR changes the PATCH route for comments to a PUT route. Making this a PUT brings our project inline with requirement SYS-020.
This PR fixes issue #93.

Update the comment PATCH route to a PUT.

---

database_scripts/gen_comments.py
database_scripts/gen_posts.py
database_scripts/gen_users.py

This PR fixes the username generation in the gen_users.py script. It also fixes some formatting issues.
- Fix the imports formatting.
- Fix the imports formatting.
- Fix the imports formatting.
- Only generate a first name, instead of a full name.
- Update username and passwd variable names for readability.

Format imports. Fix username generation.
